### ISSUE TITLE
Restaurant IDs

### ISSUE THREAD

**Issue by adityabindra** [howardbp/reservator#1]
How did you go about creating a list of restaurant IDs? Any help would be greatly appreciated. Really like what you've built here!

Thanks!

AB

**Comment by howardbp** [comment]
Hello,

I can't remember how I did it initially, but I know that the restaurant ids
are somewhere on the resy desktop api. I watched the network traffic on
chrome as I clicked around and was eventually able to write a python script
to grab all of the ids in my area. I clicked "Boston" from the resy
homepage just now, watched the network traffic and saw the api call to '
https://api.resy.com/3/collection/venues'. I attached the script that I
just hacked together. You might be able to play with the params and get the
api to return more results. Good luck!

Brice

**Comment by adityabindra** [comment]
Ahhh gotcha. Good idea going through the network traffic. I had trying to find the old documentation via Archive.org. This is way easier/better. 

Thanks!
